//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentStaffApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int feesid { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<long> Amount { get; set; }
        public string Paid { get; set; }
        public Nullable<long> Balance { get; set; }
        public string Branch { get; set; }
        public string Year { get; set; }
    
        public virtual StudentDetail StudentDetail { get; set; }
    }
}
