//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentStaffApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StaffDetail
    {
        public int StaffId { get; set; }
        [Required(ErrorMessage = "Name Field is Required")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use Alphabets only please")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Gender Field is Required")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "City Field is Required")]
        public string City { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<int> Experience { get; set; }
        [Required(ErrorMessage = "PhoneNumber Cannot be Empty")]
        [RegularExpression(@"^\(?([6-9]{1})\)?([0-9]{9})$", ErrorMessage = "phone number must starts with 9|8|7|6 and Must Contain Exact 10 digits.")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<long> Salary { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string subject { get; set; }
    }
}
