//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentStaffApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class StudentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentDetail()
        {
            this.Fees = new HashSet<Fee>();
        }

        public int StudentId { get; set; }

        [Required(ErrorMessage = "Name Field is Required")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use Alphabets only please")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Gender Field is Required")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Branch Cannot be Empty")]
        public string Branch { get; set; }
        [Required(ErrorMessage = "Year Cannot be Empty")]
        public string year { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "DOB Cannot be Empty")]
        public System.DateTime DateofBirth { get; set; }
        [Required(ErrorMessage = "PhoneNumber Cannot be Empty")]
        [RegularExpression(@"^\(?([6-9]{1})\)?([0-9]{9})$", ErrorMessage = "phone number must starts with 9|8|7|6 and Must Contain Exact 10 digits.")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Address Cannot be Empty")]
        public string Addrees { get; set; }

        
        public Nullable<long> feesAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fee> Fees { get; set; }
    }
}
